### ISSUE TITLE
Git dependencies have wrong path if they're in sub-folders

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1348]
We only trim lib/ from the start, so if you have a git dependency that's in a folder, like:

```yaml
  protobuf:
    git:
      url: git://github.com/dart-lang/protobuf.git
      path: protobuf
```

You end up with a path like `protobuf/lib/src` instead of just `src`.
