### ISSUE TITLE
QuickFix doesn't work anymore

### ISSUE THREAD

**Issue by JCKodel** [Dart-Code/Dart-Code#1926]
Example 1: (just after click Ctrl+. (shortcut for quickfix))
![image](https://user-images.githubusercontent.com/379339/63120628-08237400-bf79-11e9-9713-190506d33370.png)

The code is in the same file, and Quick Fix gives me nothing.

Example 2:
![image](https://user-images.githubusercontent.com/379339/63120893-a283b780-bf79-11e9-91c5-0c9bc99b48f7.png)

The user.dart is valid (if I uncomment this import, it will work just fine).

It only refuses to give me quick fixes for importing. It used to work before =\

What kind of information can I provide to help find the problem?

**Comment by DanTup** [comment]
I can't repro this here. Could you confirm:

- The version of Dart/Flutter you're using (shown in the status bar)
- The version of VS Code
- The version of the Dart extension
- Whether there are any errors in the dev console (click Help -> Toggle Developer Tools, then on the Console tab)
- Whether this happens in a new empty folder that has only this tiny sample in (if so, please paste the exact content so I can be sure I'm testing with exactly the same)

Thanks!

**Comment by JCKodel** [comment]
- The version of Dart/Flutter you're using (shown in the status bar)
1.7.8+hotfix.4

- The version of VS Code
1.37.1

- The version of the Dart extension
3.3.0

- Whether there are any errors in the dev console (click Help -> Toggle Developer Tools, then on the Console tab)
Opening the .dart file:
```
  ERR Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at s.getElementLocation (file:///C:/Users/jckod/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:98:403)
    at s.isCollapsed (file:///C:/Users/jckod/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:97:700)
    at q.isCollapsed (file:///C:/Users/jckod/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:962:992)
    at W.revealMarkersForCurrentActiveEditor (file:///C:/Users/jckod/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5606:566)
    at W.autoReveal (file:///C:/Users/jckod/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5606:423)
    at W.onActiveEditorChanged (file:///C:/Users/jckod/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5603:775)
    at W._register.e (file:///C:/Users/jckod/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:5602:789)
    at d.fire (file:///C:/Users/jckod/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:81:87)
    at setTimeout (file:///C:/Users/jckod/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:77:544)
```

While typing the `import` statement by hand:

```
[Extension Host] Error: Document version already has changed	at C:\Users\jckod\.vscode\extensions\naumovs.color-highlight-2.3.0\dist\extension.js:2903:17
```
No log on Ctrl+. or clicking on the error itself (to show the fix preview window).

- Whether this happens in a new empty folder that has only this tiny sample in (if so, please paste the exact content so I can be sure I'm testing with exactly the same)

I was unable to reproduce it on a new Flutter project. I tried to copy some of my source to this new project, and still works (it has improved since last update, but some instances refuses to show quick info). Guess it was fixed in the last update, I guess.

Anyway, here's the info you asked and sorry for the delay.

**Comment by DanTup** [comment]
> some instances refuses to show quick info). Guess it was fixed in the last update, I guess.

I'm not sure whether this means you still see it or not? If so, I'd definitely like to track down what's up.

**Comment by JCKodel** [comment]
Yes, in my project, intellisense fails a lot (for my files almost ever, for external packages, sometimes). But neither failed a single time in new projects, so I'm unsure what to do to pinpoint the problem =\

For example: this class exists in my project (but it is in ..\wsfx\models\user.dart). Perhaps the relative backward path? Also, wsfx folder is a submodule.

![image](https://user-images.githubusercontent.com/379339/63526343-a2ce0680-c4d5-11e9-9aa7-7d716dadaaac.png)

But autoimport seems to work fine almost every time (just sometimes it fails):
![image](https://user-images.githubusercontent.com/379339/63526498-e3c61b00-c4d5-11e9-9d38-9ebec942cc16.png)

This last one didn't work in the previous version (I'm unsure if was because VSCode update or if Dart plugin was updated).

Also, I have this:
![image](https://user-images.githubusercontent.com/379339/63526109-35ba7100-c4d5-11e9-947b-3fd54a21da5e.png)

This is a the source code of both packages, customized (notice there are overrides for them in my packages.yaml):

```yaml
name: youber_professional
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  material_design_icons_flutter: ^3.2.3895
  flutter_svg: ^0.13.1
  firebase_auth: ^0.14.0
  google_sign_in: ^4.0.4
  firebase_analytics: ^4.0.2
  flutter_secure_storage: ^3.2.1+1
  flutter_alert: ^0.4.0
  device_info: ^0.4.0+2
  path_provider: ^1.2.0
  cached_network_image: ^1.1.1
  sqflite: ^1.1.6+3
  jaguar_jwt: ^2.1.6
  package_info: ^0.4.0+6
  dio: ^2.1.13
  dio_http_cache: ^0.1.1
  dio_retry: ^0.1.8-beta
  uuid: ^2.0.2
  connectivity: ^0.4.3+6
  location: ^2.3.5
  geocoder: ^0.2.1
  floating_search_bar: ^0.2.0
  flutter_pagewise: ^1.2.3
  smooth_star_rating: ^1.0.3
  datetime_picker_formfield: ^0.4.1
  flutter_facebook_login: ^2.0.1
  in_app_purchase: ^0.2.1
  firebase_admob: ^0.9.0+3
  timeago_flutter: ^0.1.0
  timeago: ^2.0.18
  mobx: ^0.3.5
  mobx_codegen: ^0.3.3+1
  flutter_mobx: ^0.3.0+1
  intro_views_flutter: ^2.6.0
  url_launcher: ^5.1.2
  image_picker: ^0.6.1+3
  google_api_availability: ^2.0.1
  flutter_account_kit: ^0.7.0
  permission_handler: ^3.2.2
  flutter_svprogresshud: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  meta: ^1.1.0
  path: ^1.3.2
  source_gen: ^0.9.4+3
  analyzer: '>=0.33.3 <0.38.0'
  build: '>=0.12.6 <2.0.0'
  build_config: '>=0.2.6 <0.5.0'
  build_runner: ^1.0.0
  json_serializable: any
  build_verify: ^1.1.0
  build_web_compilers: '>=1.0.0 <3.0.0'
  collection: ^1.14.0
  dart_style: ^1.2.0
  logging: ^0.11.3+1
  pub_semver: ^1.4.0
  source_gen_test: ^0.1.0
  test: ^1.6.0
  yaml: ^2.1.13

dependency_overrides:
  json_annotation:
    path: lib/wsfx/builders/json_annotation
  json_serializable:
    path: lib/wsfx/builders/json_serializable

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
