### ISSUE TITLE
Lints in analysis_options.yaml without a pubspec.yaml

### ISSUE THREAD

**Issue by dcharkes** [Dart-Code/Dart-Code#2019]
Question: Are lints defined in `analysis_options.yaml` only supposed to work when there is a `pubspec.yaml` right next to it? I only see lints show up in my editor in that situation.

However, if I run the dartanalyzer from the commandline it reports lints from the first `analysis_options.yaml` it finds in a parent folder.

**Comment by DanTup** [comment]
I can't repro this - I created an analysis_options.yaml one level up from my pubspec and enabled the `avoid_as` lint, and it still shows:

<img width="926" alt="Screenshot 2019-09-30 at 3 42 18 pm" src="https://user-images.githubusercontent.com/1078012/65889300-f36c3580-e398-11e9-9e8a-af021b62cb25.png">

Can you give a specific example of what you're doing, and what the structure looks like in your explorer side bar? Thanks!

**Comment by DanTup** [comment]
I tried opening the `foo` folder directly too (so the `analysis_options.yaml` is outside of the visible/open folder) but it also still works.

**Comment by dcharkes** [comment]
I think the issue might be which `analysis_options.yaml` files are taken into account for a specific file when running `dartanalyzer` on a specific path. It is not the _most specific_ `analysis_options.yaml` apparently.

It _is_ the most specific `analysis_options.yaml` when calling `dartanalyzer` directly on that file, but it is not when calling `dartanalyzer` on an ancestor folder.

Maybe someone from the analyzer team can clarify this behavior. /cc @bwilkerson

@DanTup we run the analyzer on the opened folder (to analyze all files at the same time) instead of running the analyzer per file? That would be consistent with the command line behavior I see.

Two examples:

### Example 1

If I change `pkg/vm/analysis_options.yaml` to

```yaml
analyzer:
  exclude:
    - testcases/**
    - tool/**
linter:
  rules:
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
```

the IDE shows non-final fields/variables in for example `pkg/vm/lib/transformations/mixin_deduplication.dart`.

However, if I do not make the above change, and only create `pkg/vm/lib/transformations/analysis_options.yaml` and let it contain

```yaml
linter:
  rules:
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
```

the same file does not get lints on non-finals.

Running on the command line on the file produces lints:

```
$ dartanalyzer ./pkg/vm/lib/transformations/mixin_deduplication.dart 
Analyzing pkg/vm/lib/transformations/mixin_deduplication.dart...
  lint • Prefer final in for-each loop variable if reference is not reassigned. • pkg/vm/lib/transformations/mixin_deduplication.dart:49:14 • prefer_final_in_for_each
...
```

However, running `dartanalyzer` on `pkg/vm` does not

```
$ dartanalyzer pkg/vm
Analyzing pkg/vm...
No issues found!
```

### Example 2

Generated root `analysis_options.yaml` excludes the `tests` folder:

```yaml
analyzer:
  exclude:
    - docs/newsletter/20171103/**
    - out/**
    - pkg/front_end/testcases/**
    - runtime/**
    - samples-dev/swarm/**
    - sdk/lib/**
    - sdk_nnbd/lib/**
    - tests/**
    - third_party/observatory_pub_packages/**
    - third_party/pkg/**
    - third_party/pkg_tested/dart_style/**
    - third_party/tcmalloc/**
    - tools/apps/update_homebrew/**
    - tools/dart2js/**
    - tools/dom/**
    - tools/sdks/dart-sdk/lib/**
    - tools/status_clean.dart
    - xcodebuild/**
```

And then a modified `tests/ffi/analysis_options.yaml` includes the subfolder `tests/ffi`:

```yaml
analyzer:
  exclude:
    # Do analyze this subfolder in the tests/ even if tests/ is fully excluded.
linter:
  rules:
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
```

When running the `dartanalyzer` on a file from the command line you walk up until you find an `analysis_options.yaml`:

```
$ dartanalyzer ./tests/ffi/data_test.dart
  lint • Prefer final for variable declarations if they are not reassigned. • tests/ffi/data_test.dart:57:18 • prefer_final_locals
...
```

Curiously `dartanalyzer ./` and `dartanalyzer tests` excludes `tests/` all together, but `dartanalyzer tests/ffi` does analyze `tests/ffi/*.dart`.
