### ISSUE TITLE
todo:ignore has no effect if analysis_options.yaml at the project root dir

### ISSUE THREAD

**Issue by kinex** [Dart-Code/Dart-Code#2170]
I have placed analysis_options.yaml as follows:
./analysis_options.yaml
./app/
./package1/
./package2/

After upgrading to Flutter v1.12.13+hotfix.5 / Dart Code 3.7.1, the option "todo: ignore" stopped working (all todos are reported in Problems -tab). If I copy analysis_options.yaml to a package folder, it works again. It seems that other options work even if the file is at the project root dir.

**Comment by DanTup** [comment]
I can't reproduce this - though as I was typing you closed it - did you resolve it?

**Comment by kinex** [comment]
Sorry this was my own mistake. Possible enhancement is that VS Code should indicate clearly if analysis_options.yaml has syntax errors.

I had added `prefer_single_quotes: false` to my existing analysis_options.yaml file as follows:
```
include: package:pedantic/analysis_options.yaml
analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    todo: ignore
  exclude:
    - lib/i18n/**
    - lib/src/*.g.dart

linter:
  rules:
    - await_only_futures
    - avoid_slow_async_io
    prefer_single_quotes: false
```   

I just learned that correct syntax is this (you can’t mix list and key-value syntax in the same rules entry):
 ```
include: package:pedantic/analysis_options.yaml
analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    todo: ignore
  exclude:
    - lib/i18n/**
    - lib/src/*.g.dart

linter:
  rules:
    await_only_futures: true
    avoid_slow_async_io: true
    prefer_single_quotes: false
```   

Can I add analysis_options.yaml located at the project root level to the VS Code workspace (Flutter project with multiple packages) so that I could edit it directly in VS Code and see possible errors immediately? VS Code did not report me any format issue in analysis_options.yaml (it will report format issues if analysis_options.yaml is located in a package directory).
