### ISSUE TITLE
Package referenced with path clause is not refreshed 

### ISSUE THREAD

**Issue by dardison** [Dart-Code/Dart-Code#2371]
Hi,

I have my own library in flutter which I was reference it in another project.
The problem I have is that when I made some changes on the library project, that changes are not reflected in the project that reference it after I call flutter package get on it.
The only way I found to get the package updated was to close Visual Studio windows and reopened.

this is my pubspec.yaml  
```
name: visual_bi
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bi_framework:
   path: ../../bi_framework
  syncfusion_flutter_charts: ^18.1.42
  rxdart: ^0.24.0
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
```
My own library is **bi_framework** 

I was probably doing something wrong but I couldn't found much information about the issue.
