### ISSUE TITLE
Analysis does not pick up changes to analysis_options.yaml in parent folder

### ISSUE THREAD

**Issue by samandmoore** [Dart-Code/Dart-Code#2735]
I'm seeing that changes to my analysis_options.yaml don't seem to be causing analysis to re-run. I have to manually trigger a run with "Restart Analysis Server"

Project layout:
```
cool_app/
  /pacakge_a
  /package_b
  /flutter_app
  all_lint_rules.yaml
  analysis_options.yaml
```

here's a slice of the yaml file
```yaml
include: all_lint_rules.yaml
analyzer:
  exclude:
    - "lib/i18n/l10n/*"
    - "**/*.freezed.dart"
    - "**/*.g.dart"
  strong-mode:
    implicit-casts: false
    # implicit-dynamic: false
  errors:
    # Otherwise cause the import of all_lint_rules to warn because of some rules conflicts.
    # We explicitly enabled even conflicting rules and are fixing the conflict
    # in this file
    included_file_warning: ignore

    # It's silly to allow methods to leave out the return statement
    missing_return: error

    # Missing required fields as a warning are silly. Just call it an error.
    missing_required_param: error

    # allow having TODOs in the code
    todo: ignore

    # Ignore analyzer hints for updating pubspecs when using Future or
    # Stream and not importing dart:async
    # Please see https://github.com/flutter/flutter/pull/24528 for details.
    sdk_version_async_exported_from_core: ignore
linter:
  rules:
    # our_customizations
    one_member_abstracts: false
    constant_identifier_names: false
    avoid_function_literals_in_foreach_calls: false
    unawaited_futures: false
```

Version info:
- flutter 1.20.2
- VS Code 1.48
- Dart Code 3.13.2

Let me know if there's anything more info I can provide.
