### ISSUE TITLE
Non-LSP and LSP performance issues

### ISSUE THREAD

**Issue by danielmahon** [Dart-Code/Dart-Code#3002]
I've been having major performance issues for awhile now too (not sure how long, couple of months) but even with everything else disabled, except Flutter, the Dart extension stays at ~80% CPU at idle (without the debugger attached) and can go up to 300%+ at times, that's without LSP. With LSP I can't work very long until the analyzer just hangs completely. Let me know what info I can provide to help.

With LSP enabled, it seems as if whenever a new file is opened I mouse over a previously caught error/suggestion it triggers a LONG wait time, for example, 1+ minutes for IntelliSense.

EDIT: After watching the process monitor during startup and not doing anything else I see that the `analysis_server` does stop using CPU after like 15 minutes or so, but that seems like a super long load time...

- Issue Type: `Performance`
- Extension Name: `dart-code`
- Extension Version: `3.17.0`
- Device: `MacBook Pro (15-inch, 2017)`
- Processor: `2.9 GHz Quad-Core Intel Core i7`
- Memory: `16 GB 2133 MHz LPDDR3`
- OS Version: `macOS Big Sur 11.0.1`
- VSCode version: `1.51.1`

```
CPU % Memory (MB) PID Name
0 115 44117 code main
0 49 44120 gpu-process
0 33 44122 utility
0 262 44123 window (settings.json — ctcs (Workspace))
0 0 44409 /usr/local/bin/bash -l
0 82 44434 extensionHost
0 49 44846 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=44434
80 164 44879 /Users/daniel/Projects/flutter/bin/cache/dart-sdk/bin/dart /Users/daniel/Projects/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=VS-Code --client-version=3.17.0 --instrumentation-log-file=/Users/daniel/dartAnalyzerInstrumentation.txt
0 0 44880 bash /Users/daniel/Projects/flutter/bin/flutter daemon
2 147 44895 /Users/daniel/Projects/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/daniel/Projects/flutter/packages/flutter_tools/.packages /Users/daniel/Projects/flutter/bin/cache/flutter_tools.snapshot daemon
0 0 44970 /usr/bin/script -t 0 /dev/null xcrun xcdevice observe --both
0 33 44972 /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice observe --both
0 33 44688 watcherService
0 33 44841 searchService
0 98 44837 shared-process
0 66 44838 window (Process Explorer)
0 0 45250 /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

_Originally posted by @danielmahon in https://github.com/Dart-Code/Dart-Code/issues/2906#issuecomment-742645683_

**Comment by danielmahon** [comment]
@DanTup sent log gist to your email

pubspec.yaml
```
name: flutter_app
version: 2.1.35+274
description: CLIENT APP
publish_to: none
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  ansicolor: ^1.1.1
  app_settings: ^4.0.4
  built_collection: ^4.3.2
  connectivity: ^2.0.2
  device_info: ^1.0.0
  duration: ^2.0.15
  equatable: ^1.2.5
  ferry: ^0.9.2
  firebase_analytics: ^6.3.0
  firebase_core: ^0.5.3
  firebase_crashlytics: ^0.2.4
  firebase_dynamic_links: ^0.6.3
  firebase_messaging: ^7.0.3
  firebase_remote_config: ^0.4.3
  fl_chart: ^0.12.0
  fluro: ^1.7.8
  flutter_appauth: ^0.9.2+6
  flutter_appauth_platform_interface: ^2.0.0
  flutter_hooks: ^0.15.0
  flutter_icons: ^1.1.0
  flutter_statusbarcolor: ^0.2.3
  freezed_annotation: ^0.12.0
  fuzzy: ^0.2.3
  google_fonts: ^1.1.1
  gql: ^0.12.4
  gql_error_link: ^0.1.1-alpha+1607263101334
  gql_http_link: ^0.3.2
  gql_transform_link: ^0.1.5
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  hooks_riverpod: ^0.12.1
  intl: ^0.16.1
  jiffy: ^3.0.1
  json_annotation: ^3.1.1
  logging: ^0.11.4
  nested: ^0.0.4
  package_info: ^0.4.3+2
  path_provider: ^1.6.24
  recase: ^3.0.1
  responsive_builder: ^0.3.0
  retry: ^3.0.1
  scrollable_positioned_list: ^0.1.8
  share: ^0.6.5+4
  shimmer: ^1.1.2
  state_notifier: ^0.6.0
  timezone: ^0.5.9
  tinycolor: ^1.0.2
  universal_html: ^1.2.3
  universal_platform: ^0.1.3
  upgrader: ^2.7.3
  url_launcher: ^5.7.10
  uuid_enhanced: ^3.0.2
  websocket: ^0.0.5
  webview_flutter: ^1.0.7
dependency_overrides:
  analyzer: ^0.41.1
dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.7
  ferry_generator: ^0.3.3
  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: ^0.0.1
  freezed: ^0.12.3
  gql_code_builder: ^0.1.4+1
  hive_generator: null
  json_serializable: ^3.5.1
  lint: ^1.5.1
  test: null
flutter_icons:
  image_path: assets/app-icon.png
  android: true
  ios: true
flutter_launcher_name:
  name: HPC CTCS
flutter:
  assets:
    - assets/images/
  uses-material-design: true
```

**Comment by DanTup** [comment]
@danielmahon I can't find the log (I checked my spam folders too) - which email did you send it to? logs@dartcode.org is best. Thanks!

**Comment by danielmahon** [comment]
@DanTup resent today

**Comment by DanTup** [comment]
@danielmahon thanks!

It shows that a lot of time (around 4 minutes) was spent setting the analysis roots which seems pretty slow. It also doesn't send an `isAnalyzing: true` message until a long time after that which seems strange.

How big is the workspace you're opening (folders/files)? Is it on a local disk?

There's another open issue noting slow analyzer performance on Big Sur (https://github.com/Dart-Code/Dart-Code/issues/3005), though I haven't been able to reproduce it here.

Could you run `code --status` from a terminal while you have this project open and send me the result?

Do you see this on all projects or just this specific one? If just this specific one, is there any way you could trim it down to something you're able to share that I can test with? Thanks!

**Comment by danielmahon** [comment]
workspace has 3 folders in it, app/server/cloud functions 
flutter app is by far the biggest because of all the build artifacts and `fast_lane` integration
server and functions are both NodeJS, so no Dart there
everything on local MBP drive

ill try to test on another project when I get a chance, haven't worked on another Dart/Flutter project for a while so versions will be much older, ill try stripping my project down to a "hello world" version while keeping the build artifacts and fast_lane, and try it again without and see what happens

also see attached `analysis_options.yaml`, I'm excluding most (if not all) generated files

```bash
server [master|✚ 29…2] > code --status
Version:          Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS Version:       Darwin x64 20.1.0
CPUs:             Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)
Memory (System):  16.00GB (0.60GB free)
Load (avg):       5, 6, 5
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id ec8b9dd4-022a-44ae-b17e-09c599f97ecb
GPU Status:       2d_canvas:                  enabled
                  flash_3d:                   enabled
                  flash_stage3d:              enabled
                  flash_stage3d_baseline:     enabled
                  gpu_compositing:            enabled
                  metal:                      disabled_off
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          enabled
                  opengl:                     enabled_on
                  protected_video_decode:     unavailable_off
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %	Mem MB	   PID	Process
    1	    98	 21768	code main
    5	    49	 21771	   gpu-process
    0	    33	 21773	   utility
   12	   295	 21774	   window (retry_link_provider_2.dart — ctcs (Workspace))
    0	     0	 22060	     /usr/local/bin/bash -l
    0	    98	 22097	     extensionHost
   73	   147	 22529	       /Users/daniel/Projects/flutter/bin/cache/dart-sdk/bin/dart /Users/daniel/Projects/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --client-id=VS-Code --client-version=3.17.1 --instrumentation-log-file=/Users/daniel/dartAnalyzerInstrumentation.txt
    0	     0	 22530	       bash /Users/daniel/Projects/flutter/bin/flutter daemon
    2	   147	 22547	         /Users/daniel/Projects/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/daniel/Projects/flutter/packages/flutter_tools/.packages /Users/daniel/Projects/flutter/bin/cache/flutter_tools.snapshot daemon
    0	     0	 22641	           /usr/bin/script -t 0 /dev/null xcrun xcdevice observe --both
    0	    33	 22642	             /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice observe --both
   47	    16	 23002	           /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/Resources/bin/simctl list --json devices
    0	    33	 22582	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=22097
    0	    49	 22848	       electron_node server.js
    0	    33	 22340	     watcherService
    0	    33	 22502	     searchService
   91	   115	 22299	   shared-process
    0	     0	 23003	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Workspace Stats:
|  Window (retry_link_provider_2.dart — ctcs (Workspace))
|    Folder (functions): 38 files
|      File types: json(7) gitignore(3) js(3) map(3) ts(3) lock(3) DS_Store(1)
|                  log(1) gcloudignore(1) yaml(1)
|      Conf files: package.json(3) tsconfig.json(3) tslint.json(1)
|    Folder (server): 245 files
|      File types: ts(73) js(66) json(13) md(9) prisma(9) DS_Store(5)
|                  gitignore(2) yaml(2) bak(2) sql(2)
|      Conf files: launch.json(1) settings.json(1) package.json(1)
|                  tsconfig.json(1)
|      Launch Configs: node
|    Folder (flutter_app): more than 22281 files
|      File types: ri(14704) html(2484) gem(191) png(85) ttf(18) js(18)
|                  xml(12) dart(10) gz(9) json(8)
|      Conf files: launch.json(1) settings.json(1) package.json(1)
|      Launch Configs: dart(2)
```

```yaml
include: package:lint/analysis_options.yaml

linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # Use parameter order as in json response
    always_put_required_named_parameters_first: false

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #

    # Make constructors the first thing in every class
    sort_constructors_first: true

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true
    prefer_double_quotes: false

    # Good packages document everything
    public_member_api_docs: false

    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: false

    # Back to the 80s
    lines_longer_than_80_chars: false

    # Eventually remove these
    avoid_print: false
    constant_identifier_names: false
    sort_pub_dependencies: false

    # Support for static classes (enum-like)
    library_prefixes: false

analyzer:
  exclude:
    # generated code
    - lib/generated_plugin_registrant.dart
    - lib/**/*.freezed.dart
    - lib/**/*.graphql.dart
    - lib/**/*.g.dart
    # ferry
    - lib/**/*.gql.dart
    - lib/**/*.gql.g.dart
  errors:
    todo: ignore
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```

**Comment by btonella** [comment]
I'm having the same problem since I updated my SO to Big Sur (11.1).

**Comment by danielmahon** [comment]
@DanTup OK, after messing with it again I think I found part of the problem. After explicitly "excluding" most project level folders besides `lib` the start-up performance for LSP & non-LSP seems to significantly improve. Maybe a minute or so from project open to intellisense being responsive. (used to take 10+ minutes at times). I has also forgotten about a `node_modules` folder in the project root since I use a bunch of node scripts for the deployment, etc. So I updated the `analysis_options.yaml` with the extra excludes and it definitely works better, at-least in non-LSP... when I enable LSP the startup time is about the same but as soon as "option-click" to "go to definition", the analyzer seems to hang and restart and continues in that loop most of the time, making LSP unusable for me. Turning it off and restarting Code, it all works again.

Before, when I tried to view the analysis logs and index these extra excluded files (500k+ between android/ios/node_modules) didn't seem to show up but perhaps they were still being parsed which was causing the LONG start time...?

**updated analysis_options.yaml**
```yaml
analyzer:
  exclude:
    # generated code
    - lib/generated_plugin_registrant.dart
    - lib/**/*.freezed.dart
    - lib/**/*.graphql.dart
    - lib/**/*.g.dart
    # ferry
    - lib/**/*.gql.dart
    - lib/**/*.gql.g.dart
    # built
    - android
    - ios
    - build
    - .vscode
    - assets
    - fonts
    - node_modules
  errors:
    todo: ignore
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```
