### ISSUE TITLE
[Feature Request] Color Picker for Flutter's Color(s) similar to CSS 

### ISSUE THREAD

**Issue by osaxma** [Dart-Code/Dart-Code#3240]
For CSS files in VS Code, a color picker is provided next to the color's definition for easy selection as shown in the screenshot below:

<img width="610" alt="Screen Shot 2021-03-30 at 12 18 37 PM" src="https://user-images.githubusercontent.com/46427323/112966256-ba11b300-9152-11eb-8ae4-66d48de29b09.png">

<details><summary>example.css</summary>

```css 
#p1 {background-color: #ff0000;}            
#p2 {background-color: hsl(120, 100%, 50%);}   
#p3 {background-color: rgba(0, 4, 255, 0.733);} 
```
</details>

It'd be a handy feature for Flutter. 

Also, showing the color next to the definition may be better than showing it at the margin -- especially when multiple colors are defined on the same line.
