### ISSUE TITLE
Test runner doesn't use experiments in analysis_options.yaml

### ISSUE THREAD

**Issue by lukepighetti** [Dart-Code/Dart-Code#3243]
# MCVE

#### `lib/foo.dart`

```dart
typedef Foo = String;

Foo foo(){
  return 'foo';
}
```

#### `test/foo_test.dart`

```dart
import 'package:dart_code_3243/foo.dart';
import 'package:test/test.dart';

void main() {
  test('foo', () {
    expect(foo(), equals('foo'));
  });
}
```

#### `analysis_options.yaml`
```yaml
include: package:pedantic/analysis_options.yaml

analyzer:
  enable-experiment:
    - nonfunction-type-aliases
```

#### `pubspec.yaml`

```yaml
name: dart_code_3243
description: An MCVE for Dart-Code/Dart-Code issue 3243.

environment:
  sdk: ">=2.13.0-0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.8

```

#### Error message when clicking run tests button

<img width="433" alt="Screen Shot 2021-03-31 at 10 02 10 AM" src="https://user-images.githubusercontent.com/666539/113156679-34503f00-9208-11eb-8f86-8b322188ba14.png">

```
Failed to load "test/foo_test.dart":
Unable to spawn isolate: lib/foo.dart:1:13: Error: Can't create typedef from non-function type.
typedef Foo = String;
```

### Expected:

it uses `analysis_options.yaml` to enable experiments.

### Request for clarification

Is this intended behavior? Is there any way to enable experiments across all of Dart-Code's features including running/debugging/analyzing/testing?
