### ISSUE TITLE
Analysic Server cause high CPU usage

### ISSUE THREAD

**Issue by k3vinb0ss** [Dart-Code/Dart-Code#3662]
**Describe the bug**
dart analysis_server cause high cpu usage on both Android Studio / VSCode

**To Reproduce**
Open IDEs

**Screenshots**

<img width="1051" alt="Screen Shot 2021-11-09 at 18 06 50" src="https://user-images.githubusercontent.com/17592012/140913316-c163dca5-983f-4e46-a04a-2a83fce751f4.png">

code --status 

<img width="885" alt="Screen Shot 2021-11-09 at 18 07 18" src="https://user-images.githubusercontent.com/17592012/140913394-5d364c06-5376-4199-b253-dba6c3997b11.png">

**Versions (please complete the following information):**
 - VS Code version: 1.62.0
 - Dart extension version: v3.28.0
 - Machine: darwin-arm64

flutter doctor -v
```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-arm, locale en)
    • Flutter version 2.5.2 at /Users/kevinboss/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (6 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/kevinboss/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/kevinboss/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/kevinboss/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • iPhone (mobile) • 00008020-001D29262E21002E • ios            • iOS 14.7.1 18G82
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 95.0.4638.69
```

pubspec.yaml

```
name: 
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  yng_client:
    path: ./yng_client
  flutter_bloc: ^7.1.0
  get_it: ^7.2.0
  linter: ^1.7.0
  http: ^0.13.3
  cached_network_image: ^3.1.0
  flutter_svg: ^0.23.0+1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  equatable: ^2.0.3
  flutter_secure_storage: ^4.2.1
  flutter_dotenv: ^5.0.2
  modal_bottom_sheet: ^2.0.0
  tuple: ^2.0.0
  json_annotation: ^4.1.0
  freezed_annotation: ^0.14.3
  shimmer: ^2.0.0
  injectable: ^1.5.0
  cupertino_icons: ^1.0.2
  persistent_bottom_nav_bar: ^4.0.2
  font_awesome_flutter: ^9.2.0
  file_picker: ^4.1.6
  ai_barcode: ^3.0.1
  permission_handler: ^8.2.6
  sentry_flutter: ^6.0.1
  unorm_dart: ^0.2.0
  photo_view: ^0.13.0
  flutter_downloader: ^1.7.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.1.1
  json_serializable: ^5.0.2
  injectable_generator: ^1.5.2
  freezed: ^0.14.5
  mockito: ^5.0.16
  bloc_test: ^8.5.0
  flutter_lints: ^1.0.0
flutter:
  assets:
     - .env
     - assets/
     - assets/svg/

```
