### ISSUE TITLE
Error: Not found: 'dart:ui' when trying to run a Flutter project

### ISSUE THREAD

**Issue by noordawod** [Dart-Code/Dart-Code#3834]
Trying to run a Flutter project in VS Code yields many errors like this: `Error: Not found: 'dart:ui'`.

From looking at other issues (#2038, #1827) I understand that this is caused by trying to run a Dart project rather than a Flutter project. Well, I believe this is not the case in my project since the status bar does show Flutter and its version, in addition to selection of an emulator. The doctor also reports no issues whatsoever.

**To Reproduce**

I cannot share my code with the community (closed source), but the project opens and runs fine in both Android Studio and IntelliJ IDEA. The top-level directory contains a `pubspec.yaml` with a line reading `sdk: "flutter"`.

**Expected behavior**
The project runs as a Flutter project.

**Screenshots**

![Screenshot_2022-02-17_08-52-14](https://user-images.githubusercontent.com/4129640/154431995-b25ccfc9-cac5-414d-b625-68f3f769573f.png)

![Screenshot_2022-02-17_08-53-30](https://user-images.githubusercontent.com/4129640/154431999-d6280d86-497e-458e-80e9-a705af5e8cdc.png)

![Screenshot_2022-02-17_09-02-17](https://user-images.githubusercontent.com/4129640/154432003-0856dc1f-cd9f-41d9-b83b-9b4139063b90.png)

**Versions (please complete the following information):**
 - VS Code version: 1.64.2
 - Dart extension version: 3.34.0
 - Dart/Flutter SDK version: Flutter 2.11.0-0.0.pre.582 • channel master • Dart 2.17.0 (build 2.17.0-105.0.dev)

**Comment by DanTup** [comment]
Are you able to make a small project in the same structure that triggers this that you can share?

Could you try capturing debugging logs while reproducing this?

- Run the [**Dart: Capture Debugging Logs** command](https://dartcode.org/docs/logging/#capture-debugging-logs)
- Reproduce the issue
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here (or in a gist)

Thanks!

**Comment by noordawod** [comment]
From the log: `[9:12:04 AM] [General] [Info] Project (/path/to/workspace/app/lib/googledevel.dart) not recognised as Flutter or Web, will use Dart debugger`. I don't get why it's not being detected as Flutter, when 5 other subdirectories alongside it (`admin`, `core`, `ui`, `ui_mobile`, `db`) are detected as Flutter projects.

The structure of the workspace:

```
/path/to/workspace
|__ admin/
|     |__ pubspec.yaml
|     |__ lib/
|__ app/
|     |__ pubspec.yaml
|     |__ lib/
|__ core/
|     |__ pubspec.yaml
|     |__ lib/
|__ db/
|     |__ pubspec.yaml
|     |__ lib/
|__ ui/
|     |__ pubspec.yaml
|     |__ lib/
|__ ui_mobile/
      |__ pubspec.yaml
      |__ lib/
```

All of them are Flutter projects. Only the `app/` subdirectory is not detected as a Flutter project... I'm baffled.

**Comment by noordawod** [comment]
`.vscode/launch.json` looks like so:

```json
{
	"configurations": [
		{
			"name": "App (Devel)",
			"type": "dart",
			"request": "launch",
			"cwd": "app/",
			"program": "lib/devel.dart",
			"args": [
				"--no-sound-null-safety",
				"--enable-experiment=non-nullable",
				"--enable-experiment=nonfunction-type-aliases",
				"--enable-experiment=constructor-tearoffs"
			]
		}
	]
}
```

**Comment by noordawod** [comment]
I'll try to recreate the folder structure in a separate project... I guess it may be a bug afterall in the plugin, so happy to help.

**Comment by DanTup** [comment]
> [9:12:04 AM] [General] [Info] Project (/path/to/workspace/app/lib/googledevel.dart) not recognised as Flutter or Web, will use Dart debugger

Are you able to share the log (here or emailing me at logs@dartcode.org)? The path there is supposed to be a project folder, so having `lib/googledevel.dart` on the end looks odd. Could you also share the `pubspec.yaml` for the `app` project?

**Comment by DanTup** [comment]
Sorry, I was mistaken - we log the `program` not the project folder. But we use the `debugConfig.cwd` to check for Flutter:

https://github.com/Dart-Code/Dart-Code/blob/2f9483a71327ca010434a985b109bea7f99e8985/src/extension/providers/debug_config_provider.ts#L315

The detection of the SDK is a regex, so if your formatting is different here, perhaps that would do it:

https://github.com/Dart-Code/Dart-Code/blob/2f9483a71327ca010434a985b109bea7f99e8985/src/extension/sdk/utils.ts#L430-L436

**Comment by noordawod** [comment]
> > [9:12:04 AM] [General] [Info] Project (/path/to/workspace/app/lib/googledevel.dart) not recognised as Flutter or Web, will use Dart debugger
> 
> Are you able to share the log (here or emailing me at [logs@dartcode.org](mailto:logs@dartcode.org))? The path there is supposed to be a project folder, so having `lib/googledevel.dart` on the end looks odd. Could you also share the `pubspec.yaml` for the `app` project?

Basically, I specify a different template file to run (`flutter run -t ...`) and that's what you saw there, the `lib/googledevel.dart`). I referred to it earlier as `lib/devel.dart` mistakenly.

Anyway, I'll send you the log soon.

**Comment by noordawod** [comment]
pubspec.yaml for the app project (strippe down) is below:

```yaml
name: "flutter_app"

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
# Remove this line if you wish to publish to pub.dev
publish_to: "none"

version: "1.0.0"

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  # List of all deps comes here...

  flutter:
    sdk: "flutter"

  flutter_localizations:
    sdk: "flutter"

dev_dependencies:
  analyzer: "3.2.0"
  build_runner: "2.1.7"
  flutter_lints: "1.0.4"

flutter:
  generate: true
  uses-material-design: false
  assets:
    - "res/"
```
