### ISSUE TITLE
Add 'ignore <lint_rule> in analysis_options.yaml' as a quick fix option

### ISSUE THREAD

**Issue by osaxma** [Dart-Code/Dart-Code#4079]
**Is your feature request related to a problem? Please describe.**

There is no quick way to ignore a lint rule for an entire project especially when most of the rules are imported from a library (e.g. flutter_lints). 

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/46427323/182024205-02df3921-2134-49dc-8fb6-65dd909cda01.png)

This should add the rule to the `analysis_options.yaml` file such as:

```yaml
include: package:very_good_analysis/analysis_options.3.0.1.yaml
analyzer:
  exclude:
    - build/**
linter:
  rules:
    public_member_api_docs: false  # <~~~~~~~ add here by the quick fix
```

**Describe alternatives you've considered**
Manually copy the lint rule and add it to the file. 

The copying task is annoying because it requires hovering over the warning, dealing with a disappearing window when moving the mouse and copying a hyperlink requires some extra care to avoid clicking it. 

**Additional context**

This needs to take into account when there's more than one `analysis_options.yaml` in the project. Disabling the rule needs to go to the closest analysis_options file.   

Also this may need to check if the rule is already listed in the analysis options but with a true flag.

**Comment by DanTup** [comment]
This sounds reasonable to me. Probably it should be worded differently to "ignore" though, since it's really _disabling_ the lint when set there.

Could you file an issue for this at https://github.com/dart-lang/sdk and post the link back here? It would need to be implemented in the Dart analysis server (which is where the [existing ignores](https://github.com/dart-lang/sdk/blob/2e411e5957654a4754046798e2ec512d2d6a7037/pkg/analysis_server/lib/src/services/correction/dart/ignore_diagnostic.dart) come from).

Thanks!

**Comment by osaxma** [comment]
@DanTup totally agree -- "disable" is more appropriate. 

I filed a request @ https://github.com/dart-lang/sdk/issues/49572

Thanks!

**Comment by DanTup** [comment]
Thanks!

**Comment by osaxma** [comment]
FYI: https://dart-review.googlesource.com/c/sdk/+/352220

Though I chose `ignore` because the fix would add `ignore` such that:

```yaml
analyzer: 
  errors:
     public_member_api_docs: ignore
```

any feedback is appreciated.
