### ISSUE TITLE
Language server getting wrong method signature other than imported

### ISSUE THREAD

**Issue by canewsin** [Dart-Code/Dart-Code#4199]
**Describe the bug**
Language server getting wrong method signature other than imported

Using git version of this package
`flutter_background_service`
https://github.com/ekasetiawans/flutter_background_service/tree/9ad6ba3acf9952c53aa482708a4d099f9e33d98f

**Screenshots**
Method Signature
![Screenshot 2022-10-04 232657](https://user-images.githubusercontent.com/26790557/193892621-b16be323-202f-4d43-a540-f8370b1b96b1.png)

Usage
![Screenshot 2022-10-04 232607](https://user-images.githubusercontent.com/26790557/193892599-5a9b0a87-9dec-40bd-add9-ed844ce1d4dd.png)

**Environment:**
```yaml
  flutter_background_service: #^0.1.5
    # path: ../flutter_background_service
    git:
      url: https://github.com/ekasetiawans/flutter_background_service
      ref: 9ad6ba3acf9952c53aa482708a4d099f9e33d98f
```

**Please complete the following information:**
 - Operating System and version: Window 11
 - VS Code version: 
    >Version: 1.71.2 (user setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No
 - Dart extension version: v3.50.0
 - Dart/Flutter SDK version: `sdk: '>=2.13.0 <3.0.0'`
