### ISSUE TITLE
Set default auto import dart files with relative path, not absolute path.

### ISSUE THREAD

**Issue by erlangparasu** [Dart-Code/Dart-Code#4592]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when manually click import with relative path

**Describe the solution you'd like**
Set default auto import dart files with relative path, not absolute path.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by quyenlv-unicloud** [comment]
Did you tried enable analysis `prefer_relative_imports`? It work for me

**Comment by erlangparasu** [comment]
Thanks! @quyenlv-unicloud 

File `./.vscode/settings.json`
```
{
    "editor.codeActionsOnSave": {
        "source.fixAll": true
    }
}
```

```yaml
linter:
  rules:
    # ...
    always_use_package_imports: false
    avoid_relative_lib_imports: true
    prefer_relative_imports: true
```

Work for me too 👍
