### ISSUE TITLE
Socket error: Bad state: Cannot stop a plugin that is not running

### ISSUE THREAD

**Issue by ViShadowFiend** [Dart-Code/Dart-Code#4740]
**Describe the bug**
When I open the project in a multi-root worksapce, the dart extension will keep reporting `Socket error: Bad state: Cannot stop a plugin that is not running` every few seconds. Is there a way to know which plugin this error refers to? 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/Dart-Code/Dart-Code/assets/22252325/a58cf9fb-5428-4118-a3d4-2bc5e8bb4326)

**Please complete the following information:**
 - Operating System and version: win11 22H2
 - VS Code version: 1.82.1
 - Dart extension version: 3.72.2
 - Dart/Flutter SDK version: dart 3.0.6, flutter 3.10.16

**log**
[capture analysis server logs](https://gist.github.com/ViShadowFiend/99af4091e55ff9cfad84d807a61a9b59)

**Comment by DanTup** [comment]
There's not enough information here to tell which plugin is causing the issue. The full stack trace is:

```
Socket error
Bad state: Cannot stop a plugin that is not running.
Bad state: Cannot stop a plugin that is not running.
#0      PluginInfo.stop (package:analysis_server/src/plugin/plugin_manager.dart:233:7)
#1      PluginSession.handleNotification (package:analysis_server/src/plugin/plugin_manager.dart:882:14)
#2      ServerIsolateChannel.listen.<anonymous closure> (package:analyzer_plugin/src/channel/isolate_channel.dart:234:25)
#3      _rootRunUnary (dart:async/zone.dart:1415:13)
#4      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#9      _StreamController._add (dart:async/stream_controller.dart:650:7)
#10     _StreamController.add (dart:async/stream_controller.dart:598:5)
#11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

And this seems to occur when an error occurs in a plugin.

Could you try enabling the analysis server instrumentation log (which might record the plugin error):

- Press `F1` to open the command palette
- Run **Open Workspace Settings (JSON)**
- Add to the JSON:
  `"dart.analyzerInstrumentationLogFile": "logs/analyzer.txt"`
- Reproduce the issue
- Take a copy of the log and share it here (or email to me at logs@dartcode.org)
- Please also include a full copy of your `pubspec.yaml`/`analysis_options.yaml` files

Please be sure to remote anything sensitive from the log/files or reproduce the issue on a non-sensitive project.

**Comment by ViShadowFiend** [comment]
[](url)hello! I'm sorry I just saw the reply.

this is log
[logs/analyzer.txt](https://gist.github.com/ViShadowFiend/275e9cef74e8dcad2d4d13153d120264)

this is pubspec.yaml
[pubspec](https://gist.github.com/ViShadowFiend/a2876cf45589ba40d2b078d76cbb11e2)

this is analysis_options
[analysis_options](https://gist.github.com/ViShadowFiend/1744144d266e885edb4857a132697e67#file-analysis_options)

**Comment by DanTup** [comment]
In the log I see this error being generated:

```
1695276601813:PluginNoti: {
	"event": "plugin.error",
	"params": {
		"isFatal": false,
		"message": "Could not start the VM service: localhost:2935 is already in use.\n",
		"stackTrace": ""
	}
}:file: ///C:/Users/admin/AppData/Local/.dartServer/.plugin_manager/d1d84a9cf669a1228971692ca9be2a97/analyzer_plugin/bin/plugin.dart:
```

I think this might be happening in the custom_lint plugin. I see a change that may have been intended to fix this at https://github.com/invertase/dart_custom_lint/pull/109/files so I wonder if the issue is there (it's not clear to me if the fix worked or not, as the changelog mentions being reverted). @rrousselGit is this an issue you've had before - do you think this is a `custom_lint` issue or something the server is doing?

**Comment by DanTup** [comment]
I found mention of this same error at https://github.com/invertase/dart_custom_lint/issues/115#issuecomment-1472702181 and Remi responded that it was fixed.

@ViShadowFiend out of interest, are you on the latest version of custom_lint? Could you check which version of `custom_lint` is recorded in your `.dart_tool/package_config.json` file (or by running `flutter pub deps -s compact | select-string "- custom_lint"` from a PowerShell terminal in the project folder)?

**Comment by rrousselGit** [comment]
@DanTup The linked issue is unrelated.

The topic is this issue is something I've seen happen quite a few times, but I have no clue on where to even get started with regards to what that could be.
My guess is that it's a VScode thing though. Unless I missed something, I doubt analyzer_plugin enables plugins to show custom snackbars. So it's likely code on your side triggering it.

My assumption is that it may happen when the analyzer restart, which can happen when editing pubspec.yamls for instance.

**Comment by DanTup** [comment]
I'm not sure I understand why they can't be related - the log file shows that a plugin raises the error "Could not start the VM service:: localhost::3094 is already in use." and then there's a fatal error "Failed to start plugins":

```
1695276620444:PluginNoti:{"event"::"plugin.error","params"::{"isFatal"::false,"message"::"Could not start the VM service:: localhost::3094 is already in use.\n","stackTrace"::""}}:file::///C::/Users/admin/AppData/Local/.dartServer/.plugin_manager/d1d84a9cf669a1228971692ca9be2a97/analyzer_plugin/bin/plugin.dart::
1695276620444:PluginNoti:{"event"::"plugin.error","params"::{"isFatal"::true,"message"::"Failed to start plugins","stackTrace"::""}}:file::///C::/Users/admin/AppData/Local/.dartServer/.plugin_manager/d1d84a9cf669a1228971692ca9be2a97/analyzer_plugin/bin/plugin.dart::
1695276620445:Res:{"jsonrpc"::"2.0","method"::"window/showMessage","params"::{"message"::"Socket error:: Bad state:: Cannot stop a plugin that is not running.","type"::1}}
```

The server tries to stop the plugin, however that fails - and that error message is surfaced to the user.

There's likely a bug that the server is either stopping the plugin twice, or it is trying to stop a plugin that didn't start - but presumably this chain of events results from the plugin failing to start?

(there's also another error in the log about the `dart fix` check failing, but that happened after all of this)

**Comment by DanTup** [comment]
@rrousselGit I'm trying to see if I can reproduce this by using the example project from your repo, but I'm struggling to get it to load:

```
The package "custom_lint_example_lint" has incompatible version constraints in the project:
- "./example_lint"
  from "custom_lint_example_app" at ".\..\..\..\..\..\..\Dev\Test Projects\custom_lint_testing\dart_custom_lint\packages\custom_lint\example\pubspec.yaml".
```

The constraints were Dart 2-3, so I changed them to 3-4, but I still see this error. Pubspec looks like this:

```
name: custom_lint_example_app
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  riverpod: ^2.0.0

dev_dependencies:
  custom_lint:
  custom_lint_example_lint:
    path: ./example_lint

dependency_overrides:
  custom_lint:
    path: ../../custom_lint
  custom_lint_builder:
    path: ../../custom_lint_builder
  custom_lint_core:
    path: ../../custom_lint_core
```

I don't know if you have access to the specific versions that are wrong, but perhaps this error could include them to make it easier to track down?

**Comment by ViShadowFiend** [comment]
Sorry, what I provided before was `analysis_optins` of lib

this is `analysis_optins` of example holder
```
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude: [ build/**, lib/**.freezed.dart, lib/**.g.dart, lib/**/temp/, lib/pb/**, lib/intl/** ]

linter:
  rules:
    - always_declare_return_types
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - cast_nullable_to_non_nullable
    - directives_ordering
    - literal_only_boolean_expressions
    - null_check_on_nullable_type_parameter
    # - omit_local_variable_types
    # - only_throw_errors
    - package_api_docs
    - prefer_const_constructors
    - prefer_interpolation_to_compose_strings
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_parenthesis
    - unnecessary_statements
    - use_late_for_private_fields_and_variables
```

my current custom_lint version is 0.4.0 from `.dart_tool/package_config.json`
```
{
      "name": "custom_lint",
      "rootUri": "file:///C:/Users/admin/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/custom_lint-0.4.0",
      "packageUri": "lib/",
      "languageVersion": "2.19"
    },
    {
      "name": "custom_lint_builder",
      "rootUri": "file:///C:/Users/admin/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/custom_lint_builder-0.4.0",
      "packageUri": "lib/",
      "languageVersion": "2.19"
    },
    {
      "name": "custom_lint_core",
      "rootUri": "file:///C:/Users/admin/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/custom_lint_core-0.4.0",
      "packageUri": "lib/",
      "languageVersion": "2.19"
    },
``` 
I have tried to remove `custom_lint `from pubspec and `analysis_options`, and there are no more errors. The analyzer is running normally. Thank you very much!

**Comment by ViShadowFiend** [comment]
Sorry, what I provided before was `analysis_options` of lib

this is `analysis_options` of example holder
```
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude: [ build/**, lib/**.freezed.dart, lib/**.g.dart, lib/**/temp/, lib/pb/**, lib/intl/** ]

linter:
  rules:
    - always_declare_return_types
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - cast_nullable_to_non_nullable
    - directives_ordering
    - literal_only_boolean_expressions
    - null_check_on_nullable_type_parameter
    # - omit_local_variable_types
    # - only_throw_errors
    - package_api_docs
    - prefer_const_constructors
    - prefer_interpolation_to_compose_strings
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_parenthesis
    - unnecessary_statements
    - use_late_for_private_fields_and_variables
```

my current custom_lint version is 0.4.0 from `.dart_tool/package_config.json`
```
{
      "name": "custom_lint",
      "rootUri": "file:///C:/Users/admin/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/custom_lint-0.4.0",
      "packageUri": "lib/",
      "languageVersion": "2.19"
    },
    {
      "name": "custom_lint_builder",
      "rootUri": "file:///C:/Users/admin/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/custom_lint_builder-0.4.0",
      "packageUri": "lib/",
      "languageVersion": "2.19"
    },
    {
      "name": "custom_lint_core",
      "rootUri": "file:///C:/Users/admin/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/custom_lint_core-0.4.0",
      "packageUri": "lib/",
      "languageVersion": "2.19"
    },
``` 
I have tried to remove `custom_lint `from pubspec and `analysis_options`, and now the analyzer is running normally

But the strange thing is that during this period, vscode could not analyze/run normally due to this problem. I switched to android studio, and android studio analyzed/run normally.

**Comment by DanTup** [comment]
Looks like your `custom_lint` is out of date (the current version is 0.5.3). Can you try running `flutter pub upgrade` to see whether it updates to the latest, and see whether that solves the issue?

> But the strange thing is that during this period, vscode could not analyze/run normally due to this problem. I switched to android studio, and android studio analyzed/run normally.

I'm not sure why the difference - if I'm able to reproduce this I can try to do some debugging, but so far I wasn't able to get the `custom_lint` example project to work.

**Comment by ViShadowFiend** [comment]
@DanTup 
I tried to change
```
  custom_lint:
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
```

to

```
  custom_lint: ^0.5.3
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.1.0
```

Will still report the `Socket error: Bad state: Cannot stop a plugin that is not running`  error

**Comment by rrousselGit** [comment]
@DanTup I have no problem running custom_lint's examples.

Chances are you _shouldn't_ modify the SDK constraints. If you forgot one place, custom_lint could complain that some projects in your workspace have incompatible SDK constraints.
It currently doesn't treat Dart <3.0.0 as <4.0.0. So if one project has >2<3 and another has >3<4 then you'll get an error :)

**Comment by DanTup** [comment]
@rrousselGit thanks - it was not being able to use v3 that caused my to change them. Pulling your latest changes seems to work though.

@ViShadowFiend unfortunately I've been unable to reproduce this with a clean latest clone of the custom_lint repo, opening two copies of the `example` folder (I copied it to `example2` and updated the project names).

Are you able to share a small (but _complete_) sample project/folder that is triggering this? Ideally, with all the `.dart_tool` folders in-tact, and a saved `.code-workspace` folder that opens things exactly as reproduces the issue for you.

Thanks!

**Comment by ViShadowFiend** [comment]
@DanTup
I create a repo here: <https://github.com/ViShadowFiend/dartcode_error> 
But now, I can't reproduce the  `Socket error: Bad state: Cannot stop a plugin that is not running` error, Now there are 3 more new errors.
```
// Unable to edit document because the file was not previously opened: D:\coding\socketerror\lib_ble\example\lib\main.dart

// Socket error: Concurrent modification during iteration: _Map len:2.

// An unrecoverable error occurred and the server cannot process messages
```
Maybe it's because I used another computer or new Dart extension this time

- Operating System and version: win10 10.0.19045.3208
- VS Code version: 1.82.2
- Dart extension version: 3.74.0
- Dart/Flutter SDK version: dart 3.0.6, flutter 3.10.6

**Comment by DanTup** [comment]
@ViShadowFiend thanks - I tried with your project but wasn't able to reproduce either of the issues - I can see the plugins being loaded in the log without any errors.

That said - it still appears you're on an older version of `custom_lint` so the first think I would suggest is updating to the latest. Right now you're using `riverpod_lint: 1.3.2` which is not compatible with the latest version of custom_lint. I would recommend running the upgrade major versions command:

![image](https://github.com/Dart-Code/Dart-Code/assets/1078012/bf2496cf-70d7-49f1-8b49-e619edd8fee9)

Do this with the pubspec.yaml for `lib_ble/example/pubspec.yaml` open and it'll automatically run for that project. Alternatively, you could manually update the versions like:

```yaml
  custom_lint: ^0.5.3
  riverpod_generator: ^2.2.3
  riverpod_lint: ^2.1.1
```

I tried with both your current versions and the latest but didn't see the errors unfortunately, but there's a chance changes in the packages since the version you have might alter the behaviour (either fixing - or avoiding - the issue).
