### ISSUE TITLE
Pasting code with unknown color symbol prefixes it with `colorScheme.`

### ISSUE THREAD

**Issue by lukehutch** [Dart-Code/Dart-Code#4757]
**Describe the bug**

Select code like this:

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/c9e1de3a-2d60-4caa-8591-5e0d3256967b)

Paste into another class, where the field `Color backgroundColor` is not present:

![image](https://github.com/Dart-Code/Dart-Code/assets/811305/9d7690d5-cce9-4964-b5cf-29d955e69d4b)

The `onTap` and `icon` fields are pasted as-is. However, `backgroundColor` gets transformed into `colorScheme.background`.

This is unexpected, and frankly weird...

It may have something to do with the special rendering of colors in Dart-Code, with a color swatch thumbnail.

**Please complete the following information:**
 - Operating System and version: Linux
 - VS Code version: latest
 - Dart extension version: latest
 - Dart/Flutter SDK version: latest
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
Well that is odd. I was expecting to not be able to reproduce this, but if I create a new file with:

```dart
import 'package:flutter/material.dart';

var a = ElevatedButton.styleFrom(
  backgroundColor: backgroundColor,
);
```

And then press Save (which triggers fix-all-on-save), then I see the same thing:

```dart
import 'package:flutter/material.dart';

var a = ElevatedButton.styleFrom(
  backgroundColor: colorScheme.background,
);
```

I think this might be coming from a Flutter fix - there are a few that seems to migrate to "colorScheme.background" (such as https://github.com/flutter/flutter/pull/110162), but at a glance, they all seem to have filters that I would expect to stop them firing here. I'll try to narrow it down.

**Comment by DanTup** [comment]
Looks like it's coming from this:

```yaml
  # Changes made in https://github.com/flutter/flutter/pull/110162
  - title: "Migrate to 'ColorScheme.background'"
    date: 2022-08-24
    element:
      uris: [ 'material.dart' ]
      field: 'backgroundColor'
      inClass: 'ThemeData'
    changes:
      - kind: 'rename'
        newName: 'colorScheme.foo'
```

@bwilkerson does this seem like a bug in the data driven fixes? The fix has `inClass: 'ThemeData'` but there's no `ThemeData` involved here - there's an unresolved variable called `backgroundColor` and it's being substituted (see my comment above for a repo - that's the only thing in the file).
