### ISSUE TITLE
option to customize diagnostic severity

### ISSUE THREAD

**Issue by DetachHead** [Dart-Code/Dart-Code#5058]
**Is your feature request related to a problem? Please describe.**
i have my CI set up to fail on all analyzer diagnostics, but many of them are displayed in vscode as "information":

![image](https://github.com/Dart-Code/Dart-Code/assets/57028336/fbc172c4-1b41-4208-b74d-63055ba250cf)

"information" implies that it's not a problem, but since the CI will fail if this code is committed, i want it to show as a warning or an error. 

also, information diagnostics do not show up on the file name, but warnings and errors do:

![image](https://github.com/Dart-Code/Dart-Code/assets/57028336/f7d6b659-6c6e-4071-9340-839bb055689b)

**Describe the solution you'd like**
an option to change the severity of diagnostics

**Comment by DanTup** [comment]
You can control the severity in the `analysis_options.yaml` file:

```yaml
analyzer:
  errors:
    prefer_single_quotes: warning
```

See https://pub.dev/documentation/analysis_options/latest/#:~:text=Changing%20the%20severity%20of%20rules

> "information" implies that it's not a problem, but since the CI will fail if this code is committed

I think using `information` is correct here, since lints are not really a problem. It's not clear to me how you've set your CI up, but it might be possible you can set it to only fail on warnings/errors and not lints. That said, the lints/information messages should still show up in the Problems view - if you're not seeing them there, please let me know!

**Comment by DetachHead** [comment]
@DanTup my rules are in teh `linter.rules` section:

```yaml
linter:
    rules:
        prefer_single_quotes: true
```

attempting to move them to `analyzer.errors` like in your example seems to make the diagnostic not show up at all.

what's the difference between these two sections? is the one i'm using deprecated or something?

**Comment by DanTup** [comment]
@DetachHead the one you're using is the correct place to enable lints. The one I posted above allows you to change the severity of diagnostics by their code. It might be possible for lints to produce multiple diagnostic codes, or there may be warnings that are built-in (not lints) that you want to change the severity of.

In this case, you'll need both - one to enable the lint, and one to say that any error codes of code `prefer_single_quotes` (which happens to match the lint name) should be set to `warning`.

**Comment by DetachHead** [comment]
ah i see now, thanks.

in my case though i have lots of rules enabled, so having to duplicate them like this would be a bit annoying:

```yaml
linter:
  rules:
    prefer_single_quotes: true 
    avoid_unused_constructor_parameters: true
    avoid_dynamic_calls: true
    avoid_annotating_with_dynamic: false 
    literal_only_boolean_expressions: true
    prefer_final_locals: true
    prefer_final_parameters: true
    prefer_foreach: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_interpolation_to_compose_strings: true
    prefer_mixin: true
    public_member_api_docs: false
    require_trailing_commas: true
    sized_box_shrink_expand: true
    sort_child_properties_last: true
    sort_constructors_first: false 
    sort_unnamed_constructors_first: true
    tighten_type_of_initializing_formals: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_constructor_name: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_raw_strings: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_super_parameters: true
    use_test_throws_matchers: true
    use_to_and_as_if_applicable: true
    depend_on_referenced_packages: true
    secure_pubspec_urls: true
    sort_pub_dependencies: true
    avoid_void_async: true

analyzer:
  errors:
    prefer_single_quotes: warning
    avoid_unused_constructor_parameters: warning
    avoid_dynamic_calls: warning
    literal_only_boolean_expressions: warning
    prefer_final_locals: warning
    prefer_final_parameters: warning
    prefer_foreach: warning
    prefer_if_elements_to_conditional_expressions: warning
    prefer_interpolation_to_compose_strings: warning
    prefer_mixin: warning
    require_trailing_commas: warning
    sized_box_shrink_expand: warning
    sort_child_properties_last: warning
    sort_constructors_first: false 
    sort_unnamed_constructors_first: warning
    tighten_type_of_initializing_formals: warning
    unawaited_futures: warning
    unnecessary_await_in_return: warning
    unnecessary_constructor_name: warning
    unnecessary_lambdas: warning
    unnecessary_late: warning
    unnecessary_null_aware_assignments: warning
    unnecessary_null_checks: warning
    unnecessary_nullable_for_final_variable_declarations: warning
    unnecessary_parenthesis: warning
    unnecessary_raw_strings: warning
    use_colored_box: warning
    use_decorated_box: warning
    use_enums: warning
    use_if_null_to_convert_nulls_to_bools: warning
    use_is_even_rather_than_modulo: warning
    use_late_for_private_fields_and_variables: warning
    use_named_constants: warning
    use_raw_strings: warning
    use_setters_to_change_properties: warning
    use_string_buffers: warning
    use_super_parameters: warning
    use_test_throws_matchers: warning
    use_to_and_as_if_applicable: warning
    depend_on_referenced_packages: warning
    secure_pubspec_urls: warning
    sort_pub_dependencies: warning
    avoid_void_async: warning
```

is there a reason specifying diagnostic severities in `analyzer.errors` section can't be used to infer which rules are enabled? or should i raise a separate issue for that?
