### ISSUE TITLE
Property flavors is not allowed.yaml-schema: pubspec.yaml

### ISSUE THREAD

**Issue by danieletulone** [Dart-Code/Dart-Code#5233]
**Describe the bug**
When I add the `flavors` field to assets in pubspec.yaml, in vscode, I obtain "Property flavor is not allowed.yaml-schema: pubspec.yaml".

The edit works well in simulator, so it is only an error with pubspec schema, that don't have the "flavors".

**To Reproduce**
1. Add a flutter project in Vscode
2. Add in pubspec.yaml:
```yaml
flutter:
  assets:
    - path: /assets/develop
      flavors: 
        - prestage
```
3. Vscode gives the `Property flavor is not allowed.yaml-schema: pubspec.yaml` error message.

**Expected behavior**
To not have that error message.

**Screenshots**
<img width="304" alt="Screenshot 2024-08-25 at 19 18 55" src="https://github.com/user-attachments/assets/0b58e86d-ab85-4c59-acc9-b92438e302b0">

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

 - Operating System and version: macos / Version 14.6.1 (Build 23G93)
 - VS Code version: mac 1.92.2
 - Dart extension version: 3.94.0
 - Dart/Flutter SDK version: 3.4.3, 3.22.2
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
I can't reproduce this, but the error also doesn't look like something coming from the server - is it possible you have another extension configured to validate the pubspec.yaml?

**Comment by danieletulone** [comment]
I also tried it on Android Studio, but got the same warning message. The flavors field is not declared in the pubspec.yaml. I'm implementing it exactly as described here: https://docs.flutter.dev/deployment/flavors#conditionally-bundling-assets-based-on-flavor

**Comment by DanTup** [comment]
@danieletulone can you provide an exact copy/paste of your `pubspec.yaml`, and also if you right-click on the error in the Problems view in VS Code and choose "Copy", also paste the complete JSON it copies here?

Thanks!

**Comment by danieletulone** [comment]
It is a clean project.

So:

1. pubspec.yaml

```yaml
name: test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/common/
    - path: assets/free/
      flavors:
        - free
    - path: assets/premium/
      flavors:
        - premium
 ```
 
 2. Json of error
 ```json
 [{
	"resource": "/Users/danieletulone/test/pubspec.yaml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Property flavors is not allowed.",
	"source": "yaml-schema: pubspec.yaml",
	"startLineNumber": 25,
	"startColumn": 7,
	"endLineNumber": 25,
	"endColumn": 14
}]
```

So the error come from yaml extension that uses the pubspec schema from schemastore.org, as do also Android Studio
