### ISSUE TITLE
Can't detect Flutter project in a multi-root workspace

### ISSUE THREAD

**Issue by knopp** [Dart-Code/Dart-Code#5413]
I have a multi-root workspace where first root is Flutter engine, i.e. `/Users/Matej/Projects/flutter/flutter/engine/src/flutter` and second root is a Flutter example inside the engine, i.e. `/Users/Matej/Projects/flutter/flutter/examples/multi_window_ref_app`.

Here's the `workspace.json` file:
```
{
	"folders": [
		{
			"path": "../../../../../Projects/flutter/flutter/engine/src/flutter"
		},
		{
			"path": "../../../../../Projects/flutter/flutter/examples/multi_window_ref_app"
		}
	],
	"settings": {
		"dart.analysisExcludedFolders": [
			"/Users/Matej/Projects/flutter/flutter/engine/",
		],
		"dart.projectSearchDepth": 10,
	}
}
```

The example project gets indexed, but only as a dart project. When trying to launch it, I get 
```
Unable to launch Flutter project in a Dart-only workspace. Please open a folder closer to your Flutter project root or increase the value of the "dart.projectSearchDepth" setting.
```

Seems like a bug? The project is a Flutter project, pubspec yaml has flutter references:
```
name: multi_window_ref_app
description: "Reference app for the multi-view windowing API."
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-180.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stack_trace: ^1.11.1
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
```
