### ISSUE TITLE
Exclude field from analysis_options.yaml is not taken into account

### ISSUE THREAD

**Issue by rrousselGit** [Dart-Code/Dart-Code#601]
The `exclude` property from `analysis_options.yaml` doesn't work and still triggers warning/errors on excluded folders.

On a project with the following architecture: 
```
.pubspec.yaml
analysis_options.yaml
lib/
    main.dart  // just a simple main() {}
    app_component.dart
```

with the following `analysis_options.dart`

```
analyzer:
  exclude:
    - lib/app_component.dart

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - test_types_in_equals
```

and the following `app_component.dart`

```
class Field {}

class Bad {
  final Field someField;

  Bad(this.someField);

  @override
  bool operator ==(Object other) {
    Bad otherBad = other as Bad; // LINT
    bool areEqual = otherBad != null && otherBad.someField == someField;
    return areEqual;
  }

  @override
  int get hashCode {
    return someField.hashCode;
  }
}
```

triggers a `Test type arguments in operator ==(Object other).` on an ignored file

Using the command line `dartanalyzer .` doesn't generate this  warning unless we remove the `exclude` field.

May be related to [31344](https://github.com/dart-lang/sdk/issues/31344)
